### ISSUE TITLE
Make a debian package

### ISSUE THREAD

**Issue by baldurmen** [leapcode/amber#6]
I would be really great if this could be packaged for Debian. IMHO, gems is yet another thing not to forget to update (gem, pip, git, etc.) and having a central update vector through apt is great.

**Comment by baldurmen** [comment]
Since all the ruby deps seems to be in Debian, I tried not using any gems and only packages to make amber work.

Sadly, this fails both on Jessie and Stretch:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- RedCloth (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/pancho/programmes/amber/lib/amber/static_page/page_properties.rb:18:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/pancho/programmes/amber/lib/amber.rb:56:in `<top (required)>'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./bin/amber:18:in `rescue in <main>'
        from ./bin/amber:11:in `<main>'
```

This is the list of ruby packages I've installed:

* ruby-redcloth
* ruby-tilt
* ruby-i18n
* ruby-rdiscount
* ruby-sass
* ruby-haml
* ruby-nokogiri
